name: crystalcaves
version: "1.0-shareware"
summary: Crystal Caves Shareware
description: |
  Crystal Caves on DosBox
confinement: strict
grade: stable
base: core18

apps:
  crystalcaves:
    command: launcher
    plugs:  [pulseaudio, opengl, x11]
    extensions: [gnome-3-28]

parts:
  download:
    plugin: dump
    source: https://archive.org/download/CrystalCaves/crystal.ZIP 
    source-type: zip
    organize:
      '*.*' : game/
    stage-packages:
      - dosbox
      - libslang2

  launch:
    plugin: dump
    source: launcher

  cleanup:
    after: [download, launch]
    plugin: nil
    build-snaps:
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done
