name: crystalcaves
version: "1.0-shareware"
summary: Crystal Caves Shareware
description: |
  Crystal Caves on DosBox
confinement: strict
grade: stable
base: core20

apps:
  crystalcaves:
    command: launcher
    plugs:  [unity7, pulseaudio, opengl, network, x11]
    extensions: [gnome-3-38]

parts:
  launch:
    plugin: dump
    source: launcher
  download:
    plugin: dump
    source: https://archive.org/download/CrystalCaves/crystal.ZIP 
    source-type: zip
    organize:
      '*.*' : game/
    stage-packages:
      - dosbox
