name: lemmings
version: "1.0-demo"
summary: Lemmings Demo version
description: |
  Lemmings Demo Version
confinement: strict
grade: stable
base: core18

apps:
  lemmings:
    command: launcher
    plugs:  [audio-playback, opengl, x11]
    extensions: [gnome-3-28]

parts:
  launch:
    plugin: dump
    source: launcher
    organize:
      'launcher.bat' : shareware/LEMMINGS.BAT

  download:
    plugin: dump
    source: https://image.dosgamesarchive.com/games/lemmings-box.zip
    source-type: zip
    organize:
      'LEMMINGS/ADLIB.DAT' : shareware/
      'LEMMINGS/CLOSING.EXE' : shareware/
      'LEMMINGS/OPENING.EXE' : shareware/
      'LEMMINGS/GROUND*.DAT' : shareware/
      'LEMMINGS/MAIN.DAT' : shareware/
      'LEMMINGS/LEVEL*.DAT' : shareware/
      'LEMMINGS/ODDTABLE.DAT' : shareware/
      'LEMMINGS/VGA*.DAT' : shareware/
      'LEMMINGS/VGAL.EXE' : shareware/
    prime:
      - -LEMMINGS
      - -LEMMINGS.BAT
      - -LEMMINGS-Info-Card.txt

  dosbox-staging:
    source: https://github.com/dreamer/dosbox-staging.git
    source-branch: release/0.77.x
    source-type: git
    plugin: meson
    meson-parameters:
      - "setup"
      - "-Dprefix=/usr"
      - "-Dbuildtype=release"
      - "-Duse_fluidsynth=false"
      - "-Duse_mt32emu=false"
      - "-Duse_pcap=false"
      - "-Duse_slirp=false"
      - "-Duse_sdl2_net=false"
      - "-Duse_png=false"
    build-packages:
      - ccache
      - build-essential
      - libasound2-dev
      - libsdl2-dev
      - libopusfile-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-net-2.0-0
      - libopusfile0
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man

  cleanup:
    after: [launch, download, dosbox-staging]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done
