name: pc-epicpinball
version: "1.2-shareware"
summary: Epic Pinball Shareware
description: |
  Epic Pinball is a pinball video game played from a 2D top-down view within a scrollable window
  This version differs from https://snapcraft.io/epicpinball because it does not require a network
  connection to play the game, because the shareware is packaged in the snap.
  Buy the full version at https://www.gog.com/game/epic_pinball_the_complete_collection
confinement: strict
grade: stable
base: core18

apps:
  pc-epicpinball:
    command: launcher
    plugs:  [audio-playback, opengl, x11]
    extensions: [gnome-3-28]

parts:
  launch:
    plugin: dump
    source: launcher
  
  download:
    plugin: dump
    source: https://archive.org/download/epic_pinball_11/epic_pinball.zip
    source-type: zip
    organize:
      '*.*' : shareware/
    prime:
      - -*.DOC
      - -SETUP.EXE
      - -HELPME.EXE
      - -*.DIZ

  dosbox-staging:
    source: https://github.com/dreamer/dosbox-staging.git
    source-branch: release/0.77.x
    source-type: git
    plugin: meson
    meson-parameters:
      - "setup"
      - "-Dprefix=/usr"
      - "-Dbuildtype=release"
      - "-Duse_fluidsynth=false"
      - "-Duse_mt32emu=false"
      - "-Duse_pcap=false"
      - "-Duse_slirp=false"
      - "-Duse_sdl2_net=false"
      - "-Duse_png=false"
    build-packages:
      - ccache
      - build-essential
      - libasound2-dev
      - libsdl2-dev
      - libopusfile-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-net-2.0-0
      - libopusfile0
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
  cleanup:
    after: [launch, dosbox-staging]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done
