#!/bin/bash

if [ ! -d $SNAP_USER_DATA/shareware ]; then
	mkdir $SNAP_USER_DATA/shareware
	cp $SNAP/shareware/* $SNAP_USER_DATA/shareware/
	cp $SNAP/dosbox_distrib.conf $SNAP_USER_DATA/dosbox.conf
fi

dosbox -conf $SNAP_USER_DATA/dosbox.conf $SNAP_USER_DATA/shareware/pinball.exe -exit
