name: wolf3d
version: "1.4-shareware"
summary: Wolfenstein 3D V1.4 Shareware
description: |
  Wolfenstein 3D is a first-person shooter video game developed by id Software and published by Apogee Software. 
  Buy the full game at https://www.gog.com/game/wolfenstein_3d_and_spear_of_destiny
confinement: strict
grade: stable
base: core18

apps:
  wolf3d:
    command: launcher
    plugs:  [audio-playback, opengl, x11]
    extensions: [gnome-3-28]

parts:
  launch:
    plugin: dump
    source: launcher

  download:
    plugin: dump
    source: https://image.dosgamesarchive.com/games/wolf3d-box.zip
    source-type: zip
    organize:
      'WOLF3D/*.WL1' : shareware/
      'WOLF3D/WOLF3D.EXE' : shareware/
    prime:
      - -WOLF3D.BAT
      - -*.txt
      - -APOGEEPIX
      - -WOLF3D

  dosbox-staging:
    source: https://github.com/dreamer/dosbox-staging.git
    source-branch: release/0.77.x
    source-type: git
    plugin: meson
    meson-parameters:
      - "setup"
      - "-Dprefix=/usr"
      - "-Dbuildtype=release"
      - "-Duse_fluidsynth=false"
      - "-Duse_mt32emu=false"
      - "-Duse_pcap=false"
      - "-Duse_slirp=false"
      - "-Duse_sdl2_net=false"
      - "-Duse_png=false"
    build-packages:
      - ccache
      - build-essential
      - libasound2-dev
      - libsdl2-dev
      - libopusfile-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-net-2.0-0
      - libopusfile0
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
  cleanup:
    after: [launch, download, dosbox-staging]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done
